### Two dimensional array

In [ ]:
import numpy as np

In [2]:
sample_matrix=np.array([[50,40,1,23],[24,23,21,33],[53,76,24,7]])
sample_matrix

array([[50, 40,  1, 23],
       [24, 23, 21, 33],
       [53, 76, 24,  7]])

In [3]:
sample_matrix[1,2]

21

In [4]:
sample_matrix[2,:]

array([53, 76, 24,  7])

In [5]:
sample_matrix[2]

array([53, 76, 24,  7])

In [6]:
sample_matrix[:,3]

array([23, 33,  7])

In [7]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

In [8]:
sample_matrix[1,(1,2)]

array([23, 21])

### selection techniques

In [15]:
sample_array=np.arange(1,14)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [19]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26])

In [20]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05])

In [21]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128])

In [22]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936])

In [30]:
np.max(sample_array)

13

In [31]:
np.min(sample_array)

1

In [32]:
np.argmax(sample_array)

12

In [33]:
np.argmin(sample_array)

0

In [34]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169])

In [35]:
np.std(sample_array)

3.7416573867739413

In [36]:
np.var(sample_array)

14.0

In [39]:
array=np.random.randn(3,4)
array

array([[ 2.45909443,  0.89636001, -0.39262381,  1.24218309],
       [ 2.3215806 , -1.70627268,  0.29563487,  0.51486626],
       [-1.33887462, -0.44590152,  1.43008171, -0.05096647]])

In [41]:
np.round(array,decimals=2)

array([[ 2.46,  0.9 , -0.39,  1.24],
       [ 2.32, -1.71,  0.3 ,  0.51],
       [-1.34, -0.45,  1.43, -0.05]])

### PANDAS

### pandas dataframe and indexing

In [ ]:
import pandas as pd
import numpy as np

In [51]:
sports1=pd.Series([1,2,3,4],index=["cricket","football","baseball","g0lf"])
sports1


cricket     1
football    2
baseball    3
g0lf        4
dtype: int64

In [52]:
sports1["football"]

2

In [55]:
sports2=pd.Series([11,12,13,14,15],index=["cricket","football","baseball","basketball","golf"])
sports2

cricket       11
football      12
baseball      13
basketball    14
golf          15
dtype: int64

In [56]:
sports1+sports2

baseball      16.0
basketball     NaN
cricket       12.0
football      14.0
g0lf           NaN
golf           NaN
dtype: float64

In [73]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='score1 score2 score3 score4 score5'.split())
df1

score1    score2    score3    score4    score5
A  0.527391  0.603854  0.346600  0.085381  0.290155
B  0.848472  0.210161  0.951898  0.952987  0.896198
C  0.780396  0.609085  0.029081  0.432638  0.505784
D  0.610058  0.174493  0.647326  0.982727  0.905450
E  0.842210  0.503766  0.403173  0.600292  0.183016
F  0.386682  0.693504  0.902544  0.595943  0.946553
G  0.153199  0.541694  0.240861  0.891615  0.724794
H  0.535418  0.506239  0.715057  0.365851  0.010566

In [74]:
df1["score1"]

A    0.527391
B    0.848472
C    0.780396
D    0.610058
E    0.842210
F    0.386682
G    0.153199
H    0.535418
Name: score1, dtype: float64

In [76]:
df1["score6"]=df1["score1"]+df1["score5"]
df1

score1    score2    score3    score4    score5    score6
A  0.527391  0.603854  0.346600  0.085381  0.290155  0.817546
B  0.848472  0.210161  0.951898  0.952987  0.896198  1.744670
C  0.780396  0.609085  0.029081  0.432638  0.505784  1.286179
D  0.610058  0.174493  0.647326  0.982727  0.905450  1.515507
E  0.842210  0.503766  0.403173  0.600292  0.183016  1.025226
F  0.386682  0.693504  0.902544  0.595943  0.946553  1.333235
G  0.153199  0.541694  0.240861  0.891615  0.724794  0.877992
H  0.535418  0.506239  0.715057  0.365851  0.010566  0.545984

In [84]:
df2={'ID':['10','20','30','40'],'Name':['madhu','akhil','nares','saiss'],'profit':[20,40,60,80]}
df=pd.DataFrame(df2)
df

ID   Name  profit
0  10  madhu      20
1  20  akhil      40
2  30  nares      60
3  40  saiss      80

In [85]:
df['ID']

0    10
1    20
2    30
3    40
Name: ID, dtype: object

In [87]:
df[["ID","Name"]]

ID   Name
0  10  madhu
1  20  akhil
2  30  nares
3  40  saiss

In [92]:
df.drop(3)

Name  profit
0  madhu      20
1  akhil      40
2  nares      60

In [98]:
df=df.drop['ID',axis=1]

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (2491670272.py, line 1)